name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: python -m pip install scons
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v3
        with:
          path: godot-cpp
          key: windows-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=windows generate_bindings=yes bits=64 target=release
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=windows bits=64 target=release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: demo/addons/ropesim/bin/libropesim.windows.release.64.dll
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v3
        with:
          path: godot-cpp
          key: linux-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=linux generate_bindings=yes bits=64 target=release
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=linux bits=64 target=release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: demo/addons/ropesim/bin/libropesim.linux.release.64.so
  build_osx:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install scons yasm
      - name: Cache Godot-CPP
        id: cache-godot-cpp
        uses: actions/cache@v3
        with:
          path: godot-cpp
          key: osx-godot-cpp
      - name: Build Godot-CPP
        if: steps.cache-godot-cpp.outputs.cache-hit != 'true'
        run: scons platform=osx generate_bindings=yes bits=64 target=release
        working-directory: ./godot-cpp
      - name: Build Plugin
        run: scons platform=osx bits=64 target=release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: demo/addons/ropesim/bin/libropesim.osx.release.64.dylib
