name: CI
on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  ci:
    name: "CI"
    uses: ./.github/workflows/build.yml
    with:
      git-ref: ${{ github.ref }}

